[package]
name = "veloren-server"
version = "0.3.0"
authors = ["Joshua Barretto <joshua.s.barretto@gmail.com>"]
edition = "2018"

[dependencies]
common = { package = "veloren-common", path = "../common" }
world = { package = "veloren-world", path = "../world" }

log = "0.4.8"
specs = "0.14.2"
vek = "0.9.8"
uvth = "3.1.1"
lazy_static = "1.3.0"
scan_fmt = "0.2.3"
ron = "0.5.1"
serde = "1.0.98"
serde_derive = "1.0.98"
bincode = "1.1.4"
rand = "0.7.0"
chrono = "0.4.7"
hashbrown = { version = "0.5.0", features = ["serde", "nightly"] }
crossbeam = "0.7.2"
flate2 = "1.0"
